export interface IAd{
    id: number,
    brand: string,
    model: string,
    year: number,
    price: number,
    mileage: number,
    description: string,
    transmission: string,
    fuelType: string,
    engineDisplacement:number,
    city: string,
    created: string,
    lastUpdated:string,
    fileUrl: string,
    isFavorite:boolean,
    addedFavoriteCount:number, 
    openedPhoneCount: number,
    viewCount:number   
}
