export interface ISearchParams{
        transportTypeId?: number | null,
        brandId?: number [] | null,
        modelId?: number [],
        regionId?: number [],
        cityId?: number [],
        bodyTypeId?: number [],
        fuelTypeId?: number [],
        driveTypeId?: number [],
        transmissionId?: number [],
        colorId?: number [],
        conditionId?: number [],
        numberAxlesId?: number [],
        producingCountryId?: number [],
        wheelConfigurationId?: number [],
        priceFrom?: number,
        priceTo?: number,
        yearsFrom?: number,
        yearsTo?: number,
        mileageFrom?: number,
        mileageTo?: number,
        enginePowerFrom?: number,
        enginePowerTo?: number,
        engineDisplacementFrom?: number,
        engineDisplacementTo?: number,
        numberOfDoorsFrom?: number,
        numberOfDoorsTo?: number,
        numberOfSeatsFrom?: number,
        numberOfSeatsTo?: number,
        loadCapacityFrom?: number,
        loadCapacityTo?: number,
        trade?: boolean,
        military?: boolean,
        uncleared?: boolean,
        bargain?: boolean,
        installmentPayment?: boolean,
        orderBy?: string,
        sortBy?: string
}