export interface ISearchParams{
        transportTypeId?: number | null,
        brandId?: number [] | null,
        modelId?: number []| null,
        regionId?: number []| null,
        cityId?: number []| null,
        bodyTypeId?: number []| null,
        fuelTypeId?: number []| null,
        driveTypeId?: number []| null,
        transmissionId?: number []| null,
        colorId?: number []| null,
        conditionId?: number []| null,
        numberAxlesId?: number []| null,
        producingCountryId?: number []| null,
        wheelConfigurationId?: number []| null,
        priceFrom?: number| null,
        priceTo?: number| null,
        yearsFrom?: number| null,
        yearsTo?: number| null,
        mileageFrom?: number| null,
        mileageTo?: number| null,
        enginePowerFrom?: number| null,
        enginePowerTo?: number| null,
        engineDisplacementFrom?: number| null,
        engineDisplacementTo?: number| null,
        numberOfDoorsFrom?: number| null,
        numberOfDoorsTo?: number| null,
        numberOfSeatsFrom?: number| null,
        numberOfSeatsTo?: number| null,
        loadCapacityFrom?: number| null,
        loadCapacityTo?: number| null,
        trade?: boolean,
        military?: boolean,
        uncleared?: boolean,
        bargain?: boolean,
        installmentPayment?: boolean,
        orderBy?: string| null,
        sortBy?: string| null,
}