export interface ITransport{
    id: number,
    brand: string,
    model: string,
    year: number,
    price: number,
    mileage?: number,
    description: string,
    transmission?: string,
    fuelType?: string,
    fuelConsumptionCity?: number,
    fuelConsumptionHighway?: number,
    fuelConsumptionMixed?: number,
    engineDisplacement?:number,
    enginePower?: number,
    driveType?: string,
    city: string,
    fileUrl: string,
    bodyType?: string,
    importedFrom?: string,
    bargain?: boolean,
    trade?: boolean,
    military?: boolean,
    installmentPayment?: boolean,
    uncleared?: boolean,
    condition?: string,
    accidentHistory?: boolean,
    vincode?: string,
    color?: string,
    numberOfDoors?: number,
    numberOfSeats?: number,
    region?: string,
    mainPhoto?: string,
    userName?: string,
    galleries: [
    {
        transportGalleryId?: number,
        transportGalleryUrl?: string
    }
    ]   
}
